### PR TITLE
Proposal of new unique job titles

### PR DESCRIPTION
**Pull request by siroky**
Aim of this proposal is to fix a few things for IC career tracks:

- Ambiguity of current "Staff Engineer" job title which is used on two career tracks (engineer, technical leader). This is causing quite lot of confusion.
- We have different rules for usage of "Senior" in our career tracks. For some tracks with 4 grades, it is used on the highest grade only (e.g. Community coordinator). On other tracks it is used on 3rd grade and the highest grade uses "Staff". By unifying this, all standard career tracks with 4 grades would use the following format:
  - {Title}
  - {Title} II
  - Senior {Title}
  - Senior {Title} II
- Right now, we have no unique identifier of person's career track and progress. It's a combination of their career track and grade. With this, job title will start serving this purpose.
- As a consequence of previous point, this levels the playing field in terms of openness. For some tracks, the job title already determines person's grade openly (e.g. technical leader). For other tracks, it doesn't and e.g. "Engineering manager" can mean multiple different things. After this change, job title will determine grade for everyone, so overall, it increases openness of the framework.

### CODE REVIEW

**Comment by pbambusek** [comment]
LGTM

> Right now, we have no unique identifier of person's career track and progress. It's a combination of their career track and grade. With this, job title will start serving this purpose.

So with this, career track name will be just an internal name with no further meaning, right?

**Comment by siroky** [comment]
@pbambusek correct, career track name is already an internal name, it's only tracked in the payroll sheet, not in Bamboo. We can rename the career tracks pretty easily however we want, it's mainly used as "ID". The only thing we try to do is to name the career track reasonably so that it expresses the responsibilities.

**Review by KaliCZ — APPROVED** [review]
Apart from the fact that people with title like `Senior QA Engineer II` make us look like a distopia company assigning numbers to people, good 👍

**Comment by siroky** [comment]
@KaliCZ that's where we inspired to be honest (https://levels.fyi) 😅

**Comment by koprivajakub** [comment]
Sine now there is different title per `Grade` isn't simply better to name it:
```
IC1 - {discriminator} Engineer
IC2 - {discriminator} Engineer
IC3 - {discriminator} Engineer
IC4 - Senior {discriminator} Engineer
IC5 - Senior {discriminator} Engineer
```
?

Numbers are involved as well, but the roman `2` as a suffix seems like we could not come up with something better.
🤷‍♂️

**Review by marektresnak — APPROVED** [review]

**Comment by siroky** [comment]
I did one last update based on suggestion by @starychfojtu. I was too eager and did changes for all career tracks including the managerial, but there it didn't make as much sense as for ICs. So I decided to reduce the scope of this to IC tracks only and we'll handle the managers independently later.

**Review by KaliCZ — APPROVED** [review]
I accidentally almost merged instead of approving 😂

**Pull request merged**
